## Covariance Matrix

### What is Covariance Matrix? 
- Covariance matrix is a square matrix that displays the variance exhibited by elements of datasets and the covariance between a pair of datasets. Variance is a measure of dispersion and can be defined as the spread of data from the mean of the given dataset. Covariance is calculated between two variables and is used to measure how the two variables vary together.

- Variance covariance matrix is defined as a square matrix where the diagonal elements represent the variance and the off-diagonal elements represent the covariance. The covariance between two variables can be positive, negative, and zero. A positive covariance indicates that the two variables have a positive relationship whereas negative covariance shows that they have a negative relationship. If two elements do not vary together then they will display a zero covariance.

### Covariance Matrix Formula

#### **Population variance**:  $\frac{\sum_{1}^{n}\left ( x_{i} -\overline{x}\right )^{2} }{n-1}$

#### **Population Covariance**: $\frac{\sum_{1}^{n}\left ( x_{i} -\mu_{x}\right )\left ( y_{i}-\mu_{y} \right ) }{n}$

#### **Sample Variance**: $\frac{\sum_{1}^{n}\left ( x_{i} -\overline{x}\right )^{2} }{n-1}$


#### **Sample Covariance**: $\frac{\sum_{1}^{n}\left ( x_{i} -\overline{x}\right )^{2} }{n-1}$

where, 
- μ = mean of population data.

- x= mean of sample data.

- n = number of observations in the dataset.

- $x_i$ = observations in dataset x.



### Example
Example : Find the population covariance matrix for the following table.

| X             |      Y      |
|---------------|-------------|
| 68            |      29  |         
| 60            |      26 |       
| 58            |      30    |        
| 40            |     35   |    
  



#### Variance:

Solution: Population Variance for variable x: $\frac{1}{n} \sum_{i=1}^{n} (x_i - \mu_x)^2$

Variance for variable x:$ \frac{[(68 - 56.5)^2 + (60 - 56.5)^2 + (58 - 56.5)^2 + (40 - 56.5)^2]}{4} = 104.75$

Variance for variable y:$ \frac{[(29 - 30)^2 + (26 - 30)^2 + (30 - 30)^2 + (35 - 30)^2]}{4} = 10.5$

Covariance between variables x and y: $\frac{1}{n} \sum_{i=1}^{n} (x_i - \mu_x)(y_i - \mu_y) = -27$


The variance-covariance matrix is given as follows:

$\begin{bmatrix} 104.7 &-27 \\ -27& 10.5 \end{bmatrix}$


**Question** : How will you interpret the covariance matrix?
$\begin{bmatrix} & X & Y & Z\\ X & 500 & 320 & -40\\ Y & 320 & 340 & 0\\ Z & -40 & 0 & 800 \end{bmatrix}$

**Answer**
Solution: The variance covariance matrix can be interpreted as follows:

1) The diagonal elements 500, 340 and 800 indicate the variance in data sets X, Y and Z respectively. Y shows the lowest variance whereas Z displays the highest variance.

2) The covariance for X and Y is 320. As this is a positive number it means that when X increases (or decreases) Y also increases (or decreases)

3) The covariance for X and Z is -40. As it is a negative number it implies that when X increases Z decreases and vice - versa.

4) The covariance for Y and Z is 0. This means that there is no predictable relationship between the two data sets.


| X             |      Y      |     Z     |
|---------------|-------------|-----------|
| 15            |      12.5   |     50     |     
| 35            |      20.8   |     55     |
| 20            |      9.3    |     70     |
| 14            |      20.1   |     65     |
| 28            |      5.2    |     80     |       


We will implement this in python to find covariance matrix

In [29]:
import numpy as np

# making the matrix
X=np.array([15,35,20,14,28])
Y=np.array([12.5,15.8,9.3,20.1,5.2])
Z=np.array([50,55,70,65,80])
matrix=np.vstack((X,Y,Z))
data=matrix.T
print(data)

[[15.  12.5 50. ]
 [35.  15.8 55. ]
 [20.   9.3 70. ]
 [14.  20.1 65. ]
 [28.   5.2 80. ]]


In [30]:
# subtract the mean value from each element which makes each data point cetered at zero
data-=np.mean(data,axis=0)
print(data)

[[ -7.4   -0.08 -14.  ]
 [ 12.6    3.22  -9.  ]
 [ -2.4   -3.28   6.  ]
 [ -8.4    7.52   1.  ]
 [  5.6   -7.38  16.  ]]


In [31]:
# square every element of the matrix
squared_data=np.square(data)
print(f"squared matrix is \n",squared_data)

squared matrix is 
 [[5.47600e+01 6.40000e-03 1.96000e+02]
 [1.58760e+02 1.03684e+01 8.10000e+01]
 [5.76000e+00 1.07584e+01 3.60000e+01]
 [7.05600e+01 5.65504e+01 1.00000e+00]
 [3.13600e+01 5.44644e+01 2.56000e+02]]


In [32]:
# getting variance of "X" : sum of first column/ 5
var_X=np.sum(squared_data[:,0])/data.shape[0]
print(var_X)

64.24000000000001


In [33]:
#variance of y
var_Y=np.sum(squared_data[:,1])/data.shape[0]
print(var_Y)

26.429600000000004


In [34]:
#var z
var_Z=np.sum(squared_data[:,2])/data.shape[0]
print(var_Z)

114.0


In [35]:
#covariance of x,y
mul_xy=data[:,0] * data[:,1]
cov_xy=np.sum(mul_xy)/data.shape[0]
print(cov_xy)

-11.092


In [36]:
#covariance of yz
mul_yz=data[:,1] * data[:,2]
cov_yz=np.sum(mul_yz)/data.shape[0]
print(cov_yz)

-31.619999999999997


In [37]:
#cov_zx
mul_xz=data[:,0] * data[:,2]
cov_xz=np.sum(mul_xz)/data.shape[0]
print(cov_xz)

11.400000000000002


we evaluated the variances and the covariance values. putting these value we can now construct covariance matrix using the defintion. this will be a (3 X 3) matrix. diagonal value will be the variance of x,y,z respectively. and off diagonal value will be covariance.

In [38]:
# Construct the covariance matrix
cov_matrix = np.array([[var_X, cov_xy, cov_xz],
                       [cov_xy, var_Y, cov_yz],
                       [cov_xz, cov_yz, var_Z]])

print("covarinace variance matrix by manual procedure : \n",cov_matrix)


covarinace variance matrix by manual procedure : 
 [[ 64.24   -11.092   11.4   ]
 [-11.092   26.4296 -31.62  ]
 [ 11.4    -31.62   114.    ]]


Well we have computed covariance matrix manually and step by step. We can do this in more simple way. Moreover we can also verify if our porcess is correct.

In [39]:
# now we can square each element by multiplying matrix.T * matrix
covariance_matrix=np.dot(data.T,data)/data.shape[0]
print("covariance matrix of the data: \n",covariance_matrix)

covariance matrix of the data: 
 [[ 64.24   -11.092   11.4   ]
 [-11.092   26.4296 -31.62  ]
 [ 11.4    -31.62   114.    ]]


Now we have learned how to obtain covariance matrix easily. Now lets implement our first example and see if our code works

In [40]:
# initializing data
X=np.array([68,60,58,40],dtype=float)
Y=np.array([29,26,30,35],dtype=float)
data=np.vstack((X,Y))
data=data.T
print(data)

[[68. 29.]
 [60. 26.]
 [58. 30.]
 [40. 35.]]


In [41]:
# make the data values zero centered
data-=np.mean(data,axis=0)
print(data)

[[ 11.5  -1. ]
 [  3.5  -4. ]
 [  1.5   0. ]
 [-16.5   5. ]]


In [42]:
#now evaluationg the covariance matrix
cov_mat=np.dot(data.T,data)/data.shape[0]
print("covariance matrix is :\n",cov_mat)

covariance matrix is :
 [[104.75 -27.  ]
 [-27.    10.5 ]]


we can see that this result matches our evaluation of the example which we took in the beginning.