# Singular Value Decomposition(SVD)
Singular Value decomposition is a way of factorization of a matrix. Given a matrix $A$ of size (m X n) and we want to factorize as follows,
$A = U \cdot \Sigma \cdot V^T $

Where, 
- A=m X n matrix
- $ \Sigma$ is m X n diagonal matrix. diagonal values are eigen values
- U is m X m matrix. each colum represents eigen vectors correspondeing to eigen values. 
- $V^T$ is n X n matrix

**NB**: U and $V^T$ are orthonormal matrix. This turns out that all the columns are orthogonal and each column value is 1. Therefore $U^TU$ and  $V^TV$ are identitiy matrix(I)


## Singular Values
We can find eigen values $\lambda$ from $A^TA$ matrix. The singular value $\sigma$ which is squred root of $\lambda$ is called singular value.

**Rank**: Rank of a matrix is determined by the number of nonzero eigen values. Conversely we can say that the number of singular values is equal to the rank of the matrix. The number of non zero singular values can be maximum of size m.

## Approach to find SVD
- step 1: Evaluate U: To evaluate U we need to form $AA^T$ since from the main equation we can see that,$AV\Sigma ^T = U$
    - find eigen values of $AA^T$ matrix by solving $AA^T -\lambda I$
    - with the lambda values find corresponding eigen vectors
    - then form U by placing eigen vectors as columns ordered by vectors obtained by decreasing order eigen values.
    - then divide each element of each eigen vector by that vector value to form orthonormal vector. 


- step 2: Evaluate $V^T$: To evaluate V we need to form $A^TA$ since from the main equation we can see that,$AU^T\Sigma ^T = V$
    - these steps are same as evaluating U.


- step 3: Evaluate $\Sigma$: $\Sigma$ has the same dimension as the main matrix A. It is formed using the eigen values positioning diagonally in descending order. we only have to keep in mind that the number of nonzero eigen values can be at most m.
   

Let's implement in python

In [1]:
import numpy as np

# step 1 standardization
# initializing data
X=np.array([6,6,5,4],dtype=float)
Y=np.array([2,6,3,5],dtype=float)
data=np.vstack((X,Y))
#data=data.T # now each column represents a example
print(data)

[[6. 6. 5. 4.]
 [2. 6. 3. 5.]]


### Evaluating U

In [2]:
u_mat=np.dot(data,data.T)
print(u_mat)

[[113.  83.]
 [ 83.  74.]]


In [3]:
# find eigen vales and eigen vectors
eigen_val_u, eigen_vec_u=np.linalg.eig(u_mat)
print(f"eigen values are {eigen_val_u} \n eigen vectors are {eigen_vec_u}")

eigen values are [178.75989679   8.24010321] 
 eigen vectors are [[ 0.78380879 -0.62100223]
 [ 0.62100223  0.78380879]]


Look here the eigen values are in already decreasing order. Otherwise we will have to reorder the values as well as the vector values.

we get eigen vectors already. we just need to divide each vector value by the value of each vector. Value of a vector is ||V||=squrt(v1^2+v2^2+......)

In [4]:
U=eigen_vec_u/np.sum(eigen_vec_u**2,axis=0)
print(U)

[[ 0.78380879 -0.62100223]
 [ 0.62100223  0.78380879]]


### step 2: finding $V^T$

In [5]:
v_mat=np.dot(data.T,data)
print(v_mat)

[[40. 48. 36. 34.]
 [48. 72. 48. 54.]
 [36. 48. 34. 35.]
 [34. 54. 35. 41.]]


Eigen values and eigen vectors

In [6]:
eigen_val_v, eigen_vec_v=np.linalg.eig(v_mat)
print(f"eigen values \n{ eigen_val_v}, \n eigne vectors \n{eigen_vec_v}")

eigen values 
[ 1.78759897e+02  8.24010321e+00  2.14909590e-15 -5.95719603e-15], 
 eigne vectors 
[[-0.4446378   0.7519081   0.4577028   0.32900677]
 [-0.63042599 -0.34029599  0.18960144 -0.54678122]
 [-0.4324609   0.26252206 -0.86208233 -0.30442013]
 [-0.46673104 -0.49991501  0.10664655  0.70718684]]


Here the eigen values are in sorted(descending). Therefore the eigen vectors are also sorted.

In [7]:
# dividing by value
V=eigen_vec_v/np.sum(eigen_vec_v**2,axis=0)
print(V)

[[-0.4446378   0.7519081   0.4577028   0.32900677]
 [-0.63042599 -0.34029599  0.18960144 -0.54678122]
 [-0.4324609   0.26252206 -0.86208233 -0.30442013]
 [-0.46673104 -0.49991501  0.10664655  0.70718684]]


we need to transpose this matrix in order to get $V^T$

In [8]:
#transpose of V
V_T=np.transpose(V)
print(V_T)

[[-0.4446378  -0.63042599 -0.4324609  -0.46673104]
 [ 0.7519081  -0.34029599  0.26252206 -0.49991501]
 [ 0.4577028   0.18960144 -0.86208233  0.10664655]
 [ 0.32900677 -0.54678122 -0.30442013  0.70718684]]


###  Evaluating  $\Sigma$
 we know tha  $\Sigma$ has the shape as the main matrix A. Moreover the number of eigen values can not exceed the rank of the matrix. We evaluated $\lambda _1 ,\lambda _2$ at step 1, then $\lambda _1 ,\lambda _2,\lambda _3 ,\lambda _4$ in step 2.  Among them lamda $\lambda _1 ,\lambda _2$ are identical and  $\lambda _3 ,\lambda _4$ are near to zero .Moreover we can have at most 2(row of main matrix A) singular values. Finally singular values is equal to the squared root of the eigen values.

In [9]:
## calculating sigma values
singular_val=np.diag(np.sqrt(eigen_val_u))
print(singular_val)

[[13.37011207  0.        ]
 [ 0.          2.870558  ]]


In [10]:
#print all values together
print(f"left singular vectors\n{U},\n diagonal matrix(S)\n{singular_val} \n right singular values\n{V_T}")

left singular vectors
[[ 0.78380879 -0.62100223]
 [ 0.62100223  0.78380879]],
 diagonal matrix(S)
[[13.37011207  0.        ]
 [ 0.          2.870558  ]] 
 right singular values
[[-0.4446378  -0.63042599 -0.4324609  -0.46673104]
 [ 0.7519081  -0.34029599  0.26252206 -0.49991501]
 [ 0.4577028   0.18960144 -0.86208233  0.10664655]
 [ 0.32900677 -0.54678122 -0.30442013  0.70718684]]


we can evaluate all the factors of matrix A in a single line of code

In [11]:
u,s,v=np.linalg.svd(data)

In [12]:
print(f"left values\n{u},\nsingular values\n{s} \n right val\n{v}")

left values
[[-0.78380879 -0.62100223]
 [-0.62100223  0.78380879]],
singular values
[13.37011207  2.870558  ] 
 right val
[[-0.4446378  -0.63042599 -0.4324609  -0.46673104]
 [-0.7519081   0.34029599 -0.26252206  0.49991501]
 [-0.45999056 -0.1801256   0.86158046 -0.11680133]
 [ 0.15918578 -0.67403003  0.04169946  0.72014204]]


we can see that the right singular value in our maual procedure differs from the final approach. No worries. SVD is not unique.he signs of the right singular vectors can be flipped without affecting the correctness of the decomposition.